# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_episodes', models.IntegerField(null=True)),
                ('aired', models.DateField(null=True)),
                ('rating', models.CharField(max_length=255)),
                ('score', models.FloatField(null=True)),
                ('ranked', models.IntegerField(null=True)),
                ('popularity', models.IntegerField(null=True)),
                ('url', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='anime_genres', to='visualizacion.Genre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_studio', to='visualizacion.License'),
        ),
        migrations.AddField(
            model_name='anime',
            name='name_alternatives',
            field=models.ManyToManyField(related_name='anime_others_names', to='visualizacion.Title'),
        ),
        migrations.AddField(
            model_name='anime',
            name='name_english',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_name_english', to='visualizacion.Title'),
        ),
        migrations.AddField(
            model_name='anime',
            name='name_japanese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_name_japanese', to='visualizacion.Title'),
        ),
        migrations.AddField(
            model_name='anime',
            name='producers',
            field=models.ManyToManyField(related_name='anime_producer', to='visualizacion.Producer'),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_status', to='visualizacion.Status'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_studio', to='visualizacion.Studio'),
        ),
        migrations.AddField(
            model_name='anime',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_type', to='visualizacion.Type'),
        ),
    ]
